### PR TITLE
Completed the form part of the project. Including the title, all data…

### PR DESCRIPTION
**Pull request by Philip-Pione**
… fields, and submit button. Task-2 Completed for Sprint 1

### CODE REVIEW

**Review by CodingWithCupid — APPROVED** [review]
Looks good - approved.

**Comment by Ashuhora** [comment]
nice work.

**Review by DWilliamJ — COMMENTED** [review]
Great job. It looks good.

**Comment by Ashuhora** [comment]
It looks good.

**Review by Ashuhora — COMMENTED** [review]
It looks good.

**Pull request merged**
